# Generated by Django 3.1 on 2020-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField(blank=True)),
                ('sno', models.IntegerField(blank=True)),
                ('t0000', models.BooleanField(default=False)),
                ('t0030', models.BooleanField(default=False)),
                ('t0100', models.BooleanField(default=False)),
                ('t0130', models.BooleanField(default=False)),
                ('t0200', models.BooleanField(default=False)),
                ('t0230', models.BooleanField(default=False)),
                ('t0300', models.BooleanField(default=False)),
                ('t0330', models.BooleanField(default=False)),
                ('t0400', models.BooleanField(default=False)),
                ('t0430', models.BooleanField(default=False)),
                ('t0500', models.BooleanField(default=False)),
                ('t0530', models.BooleanField(default=False)),
                ('t0600', models.BooleanField(default=False)),
                ('t0630', models.BooleanField(default=False)),
                ('t0700', models.BooleanField(default=False)),
                ('t0730', models.BooleanField(default=False)),
                ('t0800', models.BooleanField(default=False)),
                ('t0830', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField(blank=True)),
                ('sno', models.IntegerField(blank=True)),
                ('t0900', models.BooleanField(default=False)),
                ('t0930', models.BooleanField(default=False)),
                ('t1000', models.BooleanField(default=False)),
                ('t1030', models.BooleanField(default=False)),
                ('t1100', models.BooleanField(default=False)),
                ('t1130', models.BooleanField(default=False)),
                ('t1200', models.BooleanField(default=False)),
                ('t1230', models.BooleanField(default=False)),
                ('t1300', models.BooleanField(default=False)),
                ('t1330', models.BooleanField(default=False)),
                ('t1400', models.BooleanField(default=False)),
                ('t1430', models.BooleanField(default=False)),
                ('t1500', models.BooleanField(default=False)),
                ('t1530', models.BooleanField(default=False)),
                ('t1600', models.BooleanField(default=False)),
                ('t1630', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField(blank=True)),
                ('sno', models.IntegerField(blank=True)),
                ('t1700', models.BooleanField(default=False)),
                ('t1730', models.BooleanField(default=False)),
                ('t1800', models.BooleanField(default=False)),
                ('t1830', models.BooleanField(default=False)),
                ('t1900', models.BooleanField(default=False)),
                ('t1930', models.BooleanField(default=False)),
                ('t2000', models.BooleanField(default=False)),
                ('t2030', models.BooleanField(default=False)),
                ('t2100', models.BooleanField(default=False)),
                ('t2130', models.BooleanField(default=False)),
                ('t2200', models.BooleanField(default=False)),
                ('t2230', models.BooleanField(default=False)),
                ('t2300', models.BooleanField(default=False)),
                ('t2330', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(max_length=30)),
                ('x', models.FloatField(blank=True)),
                ('y', models.FloatField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('phone', models.CharField(max_length=13)),
                ('notice', models.TextField(verbose_name='공지사항')),
                ('star', models.FloatField(blank=True, default=0.0)),
                ('com_num', models.CharField(max_length=12)),
                ('business', models.BooleanField(default=False)),
                ('seat_curr', models.IntegerField(blank=True)),
                ('seat_max', models.IntegerField(blank=True)),
                ('seat_total', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('end_time', models.TimeField(blank=True)),
                ('sno', models.IntegerField(blank=True)),
                ('cno', models.IntegerField(blank=True)),
                ('guest', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField()),
                ('uid', models.IntegerField(verbose_name='uid')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField(blank=True)),
                ('img1', models.ImageField(blank=True, upload_to='')),
                ('img2', models.ImageField(blank=True, upload_to='')),
                ('img3', models.ImageField(blank=True, upload_to='')),
                ('img4', models.ImageField(blank=True, upload_to='')),
                ('img5', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='User ID')),
                ('review', models.TextField(verbose_name='리뷰 내용')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('star', models.IntegerField(blank=True)),
                ('cno', models.IntegerField(blank=True, verbose_name='cafe number')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cno', models.IntegerField(blank=True)),
                ('rprice', models.IntegerField(blank=True)),
                ('sprice', models.IntegerField(blank=True)),
            ],
        ),
    ]
