# Generated by Django 3.1 on 2020-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200918_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='uid',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
