# Generated by Django 3.1 on 2020-09-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_inquiry_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tag',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
