# Generated by Django 3.1 on 2020-10-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_review_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='fri',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='mon',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='sat',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='sun',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='the',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='thu',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='wed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cafe',
            name='tag1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='tag2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
