# Generated by Django 3.1 on 2020-10-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201003_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='the',
            new_name='tue',
        ),
    ]
