# Generated by Django 3.1 on 2020-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20201003_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking1',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='booking2',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='booking3',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='check',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
