# Generated by Django 3.1 on 2020-10-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20201006_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
