# Generated by Django 3.1 on 2020-10-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_cafe_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField(verbose_name='cno')),
                ('age10', models.IntegerField(verbose_name='age10')),
                ('age20', models.IntegerField(verbose_name='age20')),
                ('age30', models.IntegerField(verbose_name='age30')),
                ('age40', models.IntegerField(verbose_name='age40')),
                ('age50', models.IntegerField(verbose_name='age50')),
                ('over60', models.IntegerField(verbose_name='over60')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField(verbose_name='cno')),
                ('man', models.FloatField(verbose_name='man')),
                ('woman', models.FloatField(verbose_name='woman')),
            ],
        ),
    ]
