# Generated by Django 3.1 on 2020-10-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20201014_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='check',
            name='guest',
            field=models.BooleanField(default=False),
        ),
    ]
