from django.db import models
from user.models import User
# Create your models here.

class Review(models.Model):
    uid = models.IntegerField(verbose_name='User ID')
    review = models.TextField(verbose_name='리뷰 내용')
    nickname = models.CharField(max_length=30)
    picture = models.ImageField(blank=True, null=True)
    star = models.IntegerField(blank=True)
    tag = models.CharField(max_length=15)
    cno = models.IntegerField(verbose_name='cafe number',blank=True)
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)

class Age(models.Model):
    cno = models.IntegerField(verbose_name='cno')
    age10 = models.IntegerField(verbose_name='age10',default=0)
    age20 = models.IntegerField(verbose_name='age20',default=0)
    age30 = models.IntegerField(verbose_name='age30',default=0)
    age40 = models.IntegerField(verbose_name='age40',default=0)
    age50 = models.IntegerField(verbose_name='age50',default=0)
    over60 = models.IntegerField(verbose_name='over60',default=0)

class Gender(models.Model):
    cno = models.IntegerField(verbose_name='cno')
    man = models.IntegerField(verbose_name='man',default=0)
    woman = models.IntegerField(verbose_name='woman',default=0)


class Img(models.Model):
    cno = models.IntegerField(blank=True)
    img1 = models.ImageField(blank=True)
    img2 = models.ImageField(blank=True)
    img3 = models.ImageField(blank=True)
    img4 = models.ImageField(blank=True)
    img5 = models.ImageField(blank=True)

class Notice(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField(blank=True)

class Inquiry(models.Model):
    uid = models.IntegerField(blank=True)
    title = models.CharField(max_length=50)
    body = models.TextField(blank=True)

class Cafe(models.Model):
    cafe_name = models.CharField(max_length=30)
    x = models.FloatField(blank=True)
    y = models.FloatField(blank=True)
    start_time = models.TimeField(blank=True)
    end_time = models.TimeField(blank=True)
    phone = models.CharField(max_length=13)
    notice = models.TextField(verbose_name='공지사항')
    star = models.FloatField(blank=True, default=0.0)
    com_num = models.CharField(max_length=12)
    event = models.BooleanField(blank=True)
    business = models.BooleanField(default=False)
    close = models.BooleanField(default=False)
    seat_curr = models.IntegerField(blank=True)
    seat_max = models.IntegerField(blank=True)
    seat_total = models.IntegerField(blank=True)
    tag1 = models.CharField(max_length=20,blank=True)
    tag2 = models.CharField(max_length=20,blank=True)
    event = models.TextField(verbose_name='이벤트')
    sun = models.BooleanField(blank=False)
    mon = models.BooleanField(blank=False)
    tue = models.BooleanField(blank=False)
    wed = models.BooleanField(blank=False)
    thu = models.BooleanField(blank=False)
    fri = models.BooleanField(blank=False)
    sat = models.BooleanField(blank=False)

class Check(models.Model):
    uid = models.IntegerField(blank=True)
    nickname = models.CharField(max_length=30)
    phone = models.CharField(max_length=11,blank=True)
    start_date = models.DateField(blank=True, auto_now_add=True)
    start_time = models.TimeField(blank=True)
    end_date = models.DateField(blank=True, auto_now_add=True)
    end_time = models.TimeField(blank=True)
    sno = models.IntegerField(blank=True)
    cno = models.IntegerField(blank=True)
    guest = models.BooleanField(default=False)
    check = models.BooleanField(default=False)

class Time_Sale(models.Model):
    name = models.CharField(max_length=30)
    cno = models.IntegerField(blank=True)
    rprice = models.IntegerField(blank=True)
    sprice = models.IntegerField(blank=True)

class Booking1(models.Model):
    cno = models.IntegerField(blank=True)
    sno = models.IntegerField(blank=True)
    uid = models.IntegerField(blank=True)
    phone = models.CharField(max_length=11,blank=True)
    t0000 = models.BooleanField(default=False)
    t0030 = models.BooleanField(default=False)
    t0100 = models.BooleanField(default=False)
    t0130 = models.BooleanField(default=False)
    t0200 = models.BooleanField(default=False)
    t0230 = models.BooleanField(default=False)
    t0300 = models.BooleanField(default=False)
    t0330 = models.BooleanField(default=False)
    t0400 = models.BooleanField(default=False)
    t0430 = models.BooleanField(default=False)
    t0500 = models.BooleanField(default=False)
    t0530 = models.BooleanField(default=False)
    t0600 = models.BooleanField(default=False)
    t0630 = models.BooleanField(default=False)
    t0700 = models.BooleanField(default=False)
    t0730 = models.BooleanField(default=False)
    t0800 = models.BooleanField(default=False)
    t0830 = models.BooleanField(default=False)

class Booking2(models.Model):
    cno = models.IntegerField(blank=True)
    sno = models.IntegerField(blank=True)
    uid = models.IntegerField(blank=True)
    phone = models.CharField(max_length=11,blank=True)
    t0900 = models.BooleanField(default=False)
    t0930 = models.BooleanField(default=False)
    t1000 = models.BooleanField(default=False)
    t1030 = models.BooleanField(default=False)
    t1100 = models.BooleanField(default=False)
    t1130 = models.BooleanField(default=False)
    t1200 = models.BooleanField(default=False)
    t1230 = models.BooleanField(default=False)
    t1300 = models.BooleanField(default=False)
    t1330 = models.BooleanField(default=False)
    t1400 = models.BooleanField(default=False)
    t1430 = models.BooleanField(default=False)
    t1500 = models.BooleanField(default=False)
    t1530 = models.BooleanField(default=False)
    t1600 = models.BooleanField(default=False)
    t1630 = models.BooleanField(default=False)

class Booking3(models.Model):
    cno = models.IntegerField(blank=True)
    sno = models.IntegerField(blank=True)
    uid = models.IntegerField(blank=True)
    phone = models.CharField(max_length=11,blank=True)
    t1700 = models.BooleanField(default=False)
    t1730 = models.BooleanField(default=False)
    t1800 = models.BooleanField(default=False)
    t1830 = models.BooleanField(default=False)
    t1900 = models.BooleanField(default=False)
    t1930 = models.BooleanField(default=False)
    t2000 = models.BooleanField(default=False)
    t2030 = models.BooleanField(default=False)
    t2100 = models.BooleanField(default=False)
    t2130 = models.BooleanField(default=False)
    t2200 = models.BooleanField(default=False)
    t2230 = models.BooleanField(default=False)
    t2300 = models.BooleanField(default=False)
    t2330 = models.BooleanField(default=False)

class Favorite(models.Model):
    cno = models.IntegerField(blank=False)
    uid = models.IntegerField('uid')