# Generated by Django 3.1 on 2020-09-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_wait',
            field=models.BooleanField(default=False, verbose_name='wait'),
        ),
    ]
