# Generated by Django 3.1 on 2020-10-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommendation',
            field=models.CharField(blank=True, max_length=14, verbose_name='recommendation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
