# Generated by Django 3.1 on 2020-10-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201008_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='user',
            name='r1',
            field=models.IntegerField(blank=True, default=1, verbose_name='r1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='r2',
            field=models.IntegerField(blank=True, default=1, verbose_name='r2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='r3',
            field=models.IntegerField(blank=True, default=1, verbose_name='r3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='r4',
            field=models.IntegerField(blank=True, default=1, verbose_name='r4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='r5',
            field=models.IntegerField(blank=True, default=1, verbose_name='r5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='r6',
            field=models.IntegerField(blank=True, default=1, verbose_name='r6'),
            preserve_default=False,
        ),
    ]
