# Generated by Django 3.1 on 2020-10-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201008_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='r1',
            field=models.IntegerField(blank=True, null=True, verbose_name='r1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='r2',
            field=models.IntegerField(blank=True, null=True, verbose_name='r2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='r3',
            field=models.IntegerField(blank=True, null=True, verbose_name='r3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='r4',
            field=models.IntegerField(blank=True, null=True, verbose_name='r4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='r5',
            field=models.IntegerField(blank=True, null=True, verbose_name='r5'),
        ),
        migrations.AlterField(
            model_name='user',
            name='r6',
            field=models.IntegerField(blank=True, null=True, verbose_name='r6'),
        ),
    ]
